### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by sergey-lapin** [Napoleon-BlownApart/popf-MacOS#1]
@Napoleon-BlownApart 
After running these
```
mkdir build
cd build
CC=/usr/local/opt/gcc@8/bin/gcc-8 CXX=/usr/local/opt/gcc@8/bin/g++-8 cmake ../
CC=/usr/local/opt/gcc@8/bin/gcc-8 CXX=/usr/local/opt/gcc@8/bin/g++-8 make
```
/usr/local/Cellar/gcc@8/8.4.0_2/lib/gcc/8/gcc/x86_64-apple-darwin18/8.4.0/include-fixed/stdio.h:219:10: fatal error: _ctermid.h: No such file or directory
 #include <_ctermid.h>
          ^~~~~~~~~~~~

**Comment by Napoleon-BlownApart** [comment]
I have that file under the root folder.  Have you installed Clang's command line tools?

    ./Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_ctermid.h

**Comment by sergey-lapin** [comment]
Was on 10.14 version, there is no _ctermid.h on same path, need to do update, will take a while.

**Comment by Napoleon-BlownApart** [comment]
I don't think its necessary to update MacOS.
The error is relative to your current install.  It says that `stdio.h` is not able to find the referenced file `_ctermid.h`.
You didn't answer my question about the Xcode Command Line tools.  That is usually a separate install, which sometimes, but not always, is triggered automatically subject to your response to a dialogue box that pops up.

**Comment by sergey-lapin** [comment]
@Napoleon-BlownApart I did install them but probably not correctly.
I have updated mac to 11.2.1, and installed xcode `xcode-select --install`, but now have error 
```
/usr/local/Cellar/gcc@8/8.4.0_2/include/c++/8.4.0/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
```

**Comment by sergey-lapin** [comment]
@Napoleon-BlownApart compiled finally needed to upgrade brew as well, thanks for the help!

**Comment by sergey-lapin** [comment]
@Napoleon-BlownApart Hey thanks to you I finally can run the planner, if you wanna chat please write a couple of words on 
 (sergey.lapin.k) firstname.lastname.middlename@yandex.ru. Maybe we can joint efforts on learning pddl+ or smth like that.
Will delete this message in a week.
